version: '3.7'
services:
    api:
        image: docker.pkg.github.com/thinkideaapp/sensi-backend-init/sensi-backend-init-api:master
        build: .
        ports:
            - ${API_PORT}:${API_PORT}
        volumes:
            - ./:/app
        depends_on:
            - mysql
            - redis
        restart: always
        env_file: .env
    mysql:
        image: mysql:5.6
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        env_file: .env
    redis:
        image: redis
        ports:
          - 6380:6379
